input_dir = "ticks" # директорія для файлів тіків, --input-dir="ticks"
output_dir = "bars" # директорія для збереження барів, --output-dir="bars"

symbols = "EURUSD,GBPUSD,XAUUSD,NAS100" # символи, --symbols="EURUSD,GBPUSD,XAUUSD,NAS100"
available_timeframes = "1m,2m,3m,5m,10m,15m,30m,1h,2h,4h,6h,8h,12h,D,W,M,Y" # доступні таймфрейми, статична конфігурація
timeframes = "1m,15m,1h" # таймфрейми, --timeframes="1m,15m,1h"
include_header = false # включати заголовок в файли барів, --include-header=false
ticks_timestamp_layout = "2006.01.02 15:04:05.000" # формат timestamp у файлах тіків, --ticks-timestamp-layout="2006.01.02 15:04:05.000"
bars_timestamp_layout = "2006-01-02 15:04:05" # формат timestamp у файлах барів, --bars-timestamp-layout="2006-01-02 15:04:05"

force = false # перезаписати вже існуючі бари, --force=false
write_batch_size = 1000 # розмір батча для запису даних в файл, --write-batch-size=1000
